container:
  # dockerfile: Dockerfile-test
  cpu: 4
  image: node:latest

lint_task:      
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: npm run lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: npm test -- --tap --verbose `find . -name '*.spec.js'`

ls_task:
  test_script: find . -name '*.spec.js' -ls

# test_docker_builder: 
#   only_if: $CIRRUS_TAG != ''
#   depends_on: 
#     - test
#     - lint
#   build_script: docker build --tag vly-test:latest -f Dockerfile-test
