# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Author: Andrew Somervell

name: alpha

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lang:    
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lang
      run: |
        npm ci
        cp lang/en.json lang/en.orig.json
        npm run build:lang
        diff lang/en.json lang/en.orig.json
      
  lint:        
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint
      run: |
        npm ci
        npm run lint
    
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        mongoms_download_mirror: http://downloads.mongodb.org
        mongoms_version: 4.0.5
        mongoms_disable_postinstall: 1
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
    - name: Code coverage
      run: |
        npm ci
        ./node_modules/codecov/bin/codecov --disable=gcov
    
  test:
    runs-on: ubuntu-latest
    needs: [lang, lint, coverage]
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        mongoms_download_mirror: http://downloads.mongodb.org
        mongoms_version: 4.0.5
        mongoms_disable_postinstall: 1
        ci_node_index: 0
        ci_node_total: 1
    - name: Test          
      run: |
        npm ci
        npm run test-all -- --tap
