# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Author: Andrew Somervell

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run all tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
      
    - name: Lang
      run: |
        cp lang/en.json lang/en.orig.json
        npm run build:lang
        diff lang/en.json lang/en.orig.json
          
    - name: Lint
      run: npm run lint

    - name: NPM Test
      run: npm run test-all -- --tap
      
    - name: Code Coverage
      run: ./node_modules/codecov/bin/codecov --disable=gcov
      
      env:
        CI: true
