name: V2LY master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-build:
    name: Build and push docker container
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Configure AWS credentials?
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: build
      run: ./x/aws/buildimage

    - name: deploy
      run: ./x/aws/deploy-alpha

      env:
        AWS_ACCOUNT_ID: 585172581592
        AWS_DEFAULT_REGION: ap-southeast-2
        BADGR_USERNAME: andrew+badgr@voluntarily.nz
        BADGR_PASSWORD: ${{ secrets.BADGR_PASSWORD }}
        SMTP_ID: ${{ secrets.SMTP_ID }}
        SMTP_PWD: ${{ secrets.SMTP_PWD }}
        VLY_PRIVATE_KEY: ${{ secrets.VLY_PRIVATE_KEY }}
        IMAGE_TAG_VERSION: ${{ github.head_ref }}
        HOME: /root
        APP_URL: https://alpha.voluntarily.nz
        RAYGUN_EXPRESS_SERVER_API_KEY: ${{ secrets.RAYGUN_EXPRESS_SERVER_API_KEY }}
        RAYGUN_REACT_CLIENT_API_KEY: ${{ secrets.RAYGUN_REACT_CLIENT_API_KEY }}
